# Generated by Django 5.0.6 on 2025-02-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0003_alter_job_salary'),
        ('seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Pending', max_length=10)),
                ('cover_letter', models.TextField()),
                ('resume', models.ImageField(upload_to='application/images/')),
                ('cancel', models.BooleanField(default=False)),
                ('Job_title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.industry')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeker.seeker')),
            ],
        ),
    ]
