# Generated by Django 5.0.6 on 2025-02-23 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_resume'),
        ('employer', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Job_title',
        ),
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.industry'),
        ),
    ]
