# Generated by Django 5.0.6 on 2025-02-23 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_application_job_title_application_job_title'),
        ('employer', '0003_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_title',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.industry'),
        ),
    ]
