# Generated by Django 5.0.6 on 2025-02-20 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, max_length=250, verbose_name='Link to website')),
                ('logo', models.ImageField(upload_to='employer/images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.location')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Full Time', 'full time'), ('Part Time', 'part time')], max_length=30)),
                ('job_level', models.CharField(choices=[('Entry-level', 'entry-level'), ('Intermediate ', 'intermediate '), ('Experienced', 'experienced')], max_length=30)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('updated', models.DateField()),
                ('deadline', models.DateField()),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('industry', models.ManyToManyField(to='employer.industry')),
                ('location', models.ManyToManyField(to='employer.location')),
            ],
        ),
    ]
