# Generated by Django 5.0.6 on 2025-02-20 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.location'),
        ),
    ]
