# Generated by Django 5.0.6 on 2025-02-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_remove_job_industry_remove_job_location_job_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=20),
        ),
    ]
