# Generated by Django 5.0.6 on 2025-02-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_alter_job_employer_alter_job_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('Entry-level', 'entry-level'), ('Intermediate ', 'intermediate '), ('Experienced', 'experienced')], max_length=30, null=True),
        ),
    ]
