# Generated by Django 5.0.6 on 2025-02-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_job_description_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '4 Years '), ('5 Years', '5 Years')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.CharField(choices=[('Entry-level', 'Entry-level'), ('Intermediate ', 'Intermediate '), ('Experienced', 'Experienced')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full time'), ('Part Time', 'Part time')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('10th Class', '10th Class'), ('12th Class', '12th Class'), ('Bachelore Degree', 'Bachelore Degree'), ('Master Degree', 'Master Degree '), ('Post Graduate', 'Post Graduate')], max_length=30, null=True),
        ),
    ]
