# Generated by Django 5.0.6 on 2025-02-25 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_job_experience_alter_job_job_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.location'),
        ),
    ]
