# Generated by Django 5.0.6 on 2025-02-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='about/images/')),
            ],
        ),
    ]
